### ISSUE TITLE
Feature request to turn fan other way

### ISSUE THREAD

**Issue by jmijn** [hubertjanhickinson/OrconWifiController#7]
Hi there,

I have ordered the board a long time from you and still use it every day! It works great, best money ever spent.

Now for my request, would it be possible to program the board to switch the polarity and make the fan suck fresh air from outside instead of sucking air from the rooms. This would be great in summer for my setup, so i can leave the windows closed and alternate suck and blow every hour or so.

Hope its possible! Thanks in advance!

**Comment by hubertjanhickinson** [comment]
Hi @jmijn, interesting thought! 
I really doubt if this is possible. If I look in the datasheet of a similar motor as the R3G190-RC05-20, there is no information about controlling the direction of rotation. And even if it would be possible to spin the rotor the opposite direction, it still wouldn't blow air, because it is designed for sucking.
Helaas pindakaas!

**Comment by jmijn** [comment]
That sucks 😋 thanks for clearing it up, ill close this one! Unfortunately peanutbutter!
